### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by BWibo**
This PR adds a build workflow and `Dockerfile` for a Docker image for the `citydb-tool`.

### Features

- [x] Publish to Dockerhub and Github packages
  - `3dcitydb/citydb-tool:edge`
  - `ghcr.io/3dcitydb/citydb-tool:edge`
  - Test images are here aleady: https://github.com/BWibo/citydb-tool/pkgs/container/citydb-tool
  - Currently, only an `edge` image build from the latest commit to `main`
- [x] Build for common platforms `amd64`, `arm64`, `arm/v7`
- [x] Use new base image, as OpenJDK is deprecated, see https://hub.docker.com/_/openjdk
- [x] Document new image

### CODE REVIEW

**Comment by BWibo** [comment]
@clausnagel I don't have any rights on this repo jet. That's why the PR is coming from a fork.

@clausnagel @yaozhihang @thomashkolbe

The image works the same way the old `impexp` image did:

```shell
docker run --rm --name impexp [-i -t] \
    [-e CITYDB_TYPE=postgresql|oracle] \
    [-e CITYDB_HOST=the.host.de] \
    [-e CITYDB_PORT=5432] \
    [-e CITYDB_NAME=theDBName] \
    [-e CITYDB_SCHEMA=theCityDBSchemaName] \
    [-e CITYDB_USERNAME=theUsername] \
    [-e CITYDB_PASSWORD=theSecretPass] \
    [-v /my/data/:/data] \
  3dcitydb/citydb-tool[:TAG] COMMAND
```

You can use these images for testing already:
- `bwibo/citydb-tool:edge`
- `ghcr.io/bwibo/citydb-tool:edge`

There are some points to discuss:

- Where should I document the new image? For now, I suggest just adding a section in `README.md` of this repo. Then everybody can test it, until the new docs are ready.
- @clausnagel Are the ENV vars listed above still the same?
- I switched the base image to https://hub.docker.com/_/eclipse-temurin, because OpenJDK is deprecated. There are other options too ([see here for instance](https://hub.docker.com/_/openjdk)). Probably, this base image will be fine. It offers support for all common platforms and seems to be updated regularly.
- We might switch to Java 17 or 21, see #2 
- Do we have use for docker images built for pushes to PRs?
- @thomashkolbe You are using a ARM64 arch Mac, right? The image should now natively support this (see [here](https://github.com/BWibo/citydb-tool/pkgs/container/citydb-tool)). It would be great if you could test it and confirm that this works and ARM64 is not emulated.

**Comment by clausnagel** [comment]
Hi @BWibo, thanks for this PR. I try to answer all your questions below.

- Your access rights to the repository should be fixed. Please confirm.
- Documentation in the README until we find a proper new place is fine with me.
-  The ENV variables are ok except for `CITYDB_TYPE`. We currently only support PostgreSQL, so we have skipped this ENV variable for the moment.
- Eclipse Temurin as base image is fine with me.
- For the Docker image, we can easily use Java 17 or 21. For the source code in general, I will answer in #2 directly.
- I personally don't need Docker images built for pushes in a PR.

**Comment by yaozhihang** [comment]
The docker image build and running the citydb-tool work very nice in my tests on a WIN10 PC.

**Comment by BWibo** [comment]
From my side this is ready. I added a workflow to build release images too. To make it work, we need to use versioning conforming to semver. E.g. `0.5.0-beta`, `0.5.0`

It works like this:

- Images are built for releases and pre-releases.
  - If an image is a release, it will be tagged as `latest` too.
  - If it is a pre-release (checkbox in Github UI [release page](https://github.com/3dcitydb/citydb-tool/releases/new), it will not be tagged as latest.

**Note:** The workflow does not apply to existing tags. So we need to create a new release to build a first release image.

**Comment by BWibo** [comment]
Ah wait, there is one small thing to fix.

**Comment by BWibo** [comment]
I could not manage to re-open this. It is now: #4

**Pull request merged**
