### PR TITLE
added basic build CI workflow

### PR DESCRIPTION
**Pull request by beneschwab**
In case you need a first and basic CI workflow for building the tool.
Let me know, if I should adapt something to your needs.

### CODE REVIEW

**Comment by yaozhihang** [comment]
@beneschwab thanks, looks good to me.

**Comment by yaozhihang** [comment]
I think you could also add the status badge into the README file.

**Comment by beneschwab** [comment]
I just added the badge to the README

**Comment by clausnagel** [comment]
I guess we are ready to merge. @yaozhihang?

**Comment by yaozhihang** [comment]
> I guess we are ready to merge. @yaozhihang?

yes, let's merge.

**Pull request merged**
